apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mcw-oss-paas-devops
  name: mcw-oss-paas-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcw-oss-paas-devops
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mcw-oss-paas-devops
      name: mcw-oss-paas-devops
    spec:
      containers:
      - image: bestforyouregistryoss.azurecr.io/best-for-you-organics
        env:
        - name: NODE_ENV
          value : production
        imagePullPolicy: Always
        name: mcw-oss-paas-devops
        ports:
        - containerPort: 3000
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20          
        resources:
          requests:
            cpu: 1000m
            memory: 128Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mcw-oss-paas-devops
  name: mcw-oss-paas-devops
spec:
  ports:
  - name: web-traffic
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: mcw-oss-paas-devops
  sessionAffinity: None
  type: LoadBalancer