apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mcw-oss-paas-devops
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mcw-oss-paas-devops
    spec:
      containers:
      - name: mcw-oss-paas-devops
        image: bestforyouregistryoss.azurecr.io/best-for-you-organics:v1
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: mcw-oss-paas-devops
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: mcw-oss-paas-devops