apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mcw-oss-paas-devops
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  miniReadySeconds: 5
  template:
    metadata:
      labels:
        app: mcw-oss-paas-devops
    spec:
      containers:
      - image: bestforyouregistryoss.azurecr.io/best-for-you-organics
        env:
        - name: NODE_ENV
          value: production
        imagePullPolicy: Always
        name: mcw-oss-paas-devops
        ports:
        - containerPort: 3000      
        resources:
          requests:
            cpu: 1000m
            memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: mcw-oss-paas-devops
spec:
  ports:
  - port: 3000
  selector:
    app: mcw-oss-paas-devops
  type: LoadBalancer